album/urls.py
from django.contrib import admin
from django.urls import path, include
from album.views import inicio 

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", inicio, name="inicio"),
    path("fotos/", include("apps.fotos.urls")),
    path("articulos/", include("apps.articulos.urls")),
    path("api-futbol/", include("apps.apiFutbol.urls"))
    
]

apps/apiFutbol/urls.py
from django.urls import path
from . import views

app_name= "apps_apiFutbol"

urlpatterns = [ 
        path("partidos", views.partidos , name="partidos"),
        path("registrar-apuesta", views.registrarApuesta, name="registrar_apuesta"),
        path("historial", views.traerApuestas, name="traerApuestas")
]

apps/articulos/urls.py
from django.urls import path
from . import views

app_name ="apps_articulos"

urlpatterns=[
    path("noticias", views.articulos, name="articulos"),
    path('detalle/<int:id>/', views.DetalleArticulo, name="DetalleArticulo")
]

apps/fotos/urls.py
from django.urls import path
from . import views

app_name= 'apps_fotos'

urlpatterns = [
    path('album-evangelion/', views.album, name='album')
]

apps/apiFutbol/models.py
from django.db import models

class Apuesta(models.Model):
    nombreLocal = models.CharField(max_length=60)
    nombreVisitante = models.CharField(max_length=60)
    ganador = models.CharField(max_length=60)
    odd = models.FloatField()
    apuesta = models.IntegerField()
    premio = models.IntegerField()
    finalizada = models.BooleanField(default=False)
    idFixture = models.IntegerField()
    estado = models.CharField(max_length=25)
    fecha = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.ganador

apps/articulos/models.py
from django.db import models

class articulo(models.Model):
    titulo = models.CharField(max_length=80)
    fechaPublicacion = models.DateField()
    resumen = models.CharField(max_length=200)
    detalle = models.CharField(max_length=1000)
    foto = models.CharField(max_length=150)
    estadoPublicado= models.BooleanField(default=True)

    def __str__(self):
        return self.titulo  

apps/fotos/models.py
from django.db import models

class Mifoto(models.Model):
    nombre = models.CharField(max_length=90)
    descripcion = models.CharField( max_length=2000 )
    imageurl = models.CharField(max_length=120)
    publish = models.BooleanField(default=True)
    date = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.nombre

album/views.py
from django.shortcuts import render

def inicio(request):
    return render(request,"pages/index.html",{})

apps/apiFutbol/views.py
from django.shortcuts import render, redirect
from .services.apiFutbol import getPartidos, getOdds, partidosOdds
from .models import Apuesta
from django.http import  JsonResponse
from .services.crearApuesta import crearApuesta

def partidos(request):
    
   responseDataPartidos = getPartidos()
   oddLocal, oddVisitante=  getOdds()
   partidosOdd= partidosOdds(responseDataPartidos, oddLocal, oddVisitante)
   #return render(
        #request, 
        #"apiFutbol/partidosPrueba.html", 
        #{
            #'responseDataPartidos': responseDataPartidos, 
            #'oddLocal': oddLocal, 
            #'oddVisitante': oddVisitante
        #}
    #)
     
   if not responseDataPartidos:  # Si hubo un error en la API
        return render(request, "apiFutbol/partidos.html", {'error': "Error al obtener datos"})
   return render(request, "apiFutbol/partidos.html", 
                { 'responseDataPartidos': responseDataPartidos, 
                'partidosOdd': partidosOdd})

def registrarApuesta(request):
    
    if request.method == "POST":
        try:
            nombreLocal = request.POST['nombreLocal']
            nombreVisitante = request.POST['nombreVisitante']
            ganador = request.POST['nombreGanador']
            odd = float(request.POST['odd'])
            apuesta = int(request.POST['cantidadApostar'])
            premio = int(odd*apuesta)
            finalizada = False
            idFixture = int(request.POST['idPartido'])
            estado="En Juego"
            crearApuesta(nombreLocal, nombreVisitante, ganador, odd, apuesta, premio, finalizada, idFixture, estado)
            return redirect("apps_apiFutbol:partidos")
        
        except ValueError:
            return JsonResponse({"error": "Dato inválido"}, status=400)
        
    return JsonResponse({"error": "Método no permitido"}, status=405)
    
        
def traerApuestas(request):
    listaApuestas = Apuesta.objects.all()
    return render(request, 'apiFutbol/historial.html', {'listaApuestas': listaApuestas} )

apps/articulos/views.py
from django.shortcuts import render, get_object_or_404
from django.shortcuts import render
from .models import articulo

def articulos(request):
    mis_articulos = articulo.objects.all()
    return render(request,"articulos/articulos.html", {"articulos":mis_articulos} )

def DetalleArticulo(request, id):
    Articulo = get_object_or_404(articulo, id=id)
    return render(request, 'articulos/DetalleArticulo.html' , {'articulo': Articulo})

apps/fotos/views.py
from django.shortcuts import render

from .models import Mifoto

def album(request):
    fotos = Mifoto.objects.all()
    return render(request, "fotos/index.html", {"fotos":fotos})

apps/articulos/templates/articulos/DetalleArticulo.html
{%extends 'layout/base.html'%}
{%load static%}
{%block title%}Articulos{%endblock%}
{% block content %}
<img src="{{articulo.foto}}" class="mx-auto d-block w-75 h-auto p-3 m" alt="">
        <h1 class="mt-4">{{articulo.titulo}}</h1>
        <p class="fs-4 mb-3">{{ articulo.fechaPublicacion|date:"d/m/Y" }}</p>
        <hr>
        <p>{{articulo.detalle}}</p>
        <hr>
{% endblock %}

apps/articulos/templates/articulos/articulos.html
{%extends 'layout/base.html'%}
{%load static%}
{%block title%}Articulos{%endblock%}
{% block content %}

<h1 class="mb-2">Noticias</h1>
<p class="mb-5 fs-4">En esta sección encontrará las noticias más destacadas de los últimos días en Colombia.</p>
<section class="articles mb-5">
    {% for articulo in articulos %}
    <article>
        <figure>
            <img src="{{articulo.foto}}" alt="Imagen de artículo">
        </figure>
        <div class="article-body">
            <h2>{{articulo.titulo}}</h2>
            <p >{{ articulo.fechaPublicacion|date:"d/m/Y" }}</p>
            <p>{{articulo.resumen}}</p>
            <a href="{% url 'apps_articulos:DetalleArticulo' articulo.id%}" class="read-more">
                Leer más
                <svg xmlns="http://www.w3.org/2000/svg" class="icon" viewBox="0 0 20 20" fill="currentColor">
                    <path fill-rule="evenodd"
                        d="M12.293 5.293a1 1 0 011.414 0l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-2.293-2.293a1 1 0 010-1.414z"
                        clip-rule="evenodd" />
                </svg>
            </a>
        </div>
    </article>
    {% empty %}
    <p>No hay fotos disponibles.</p>
    {% endfor %}

   
</section>

{% endblock %}

apps/fotos/templates/fotos/index.html
{%extends 'layout/base.html'%}
{%load static%}
{%block title%}Evangelion{%endblock%}
{% block content %}
<h1>Personajes Evangelion</h1>

<div class="content-wrapper">

    
    <div class="row justify-content-center mb-4 mt-5">
        {% for foto in fotos %}
        <div class="col-lg-3 col-md-4 col-sm-6 col-12 mt-4 mb-5">

            <div class="card-container">
                <div class="card">
                    <img src="{{ foto.imageurl }}" alt="Imagen de perfil" class="card-img">
                    <p class="title">{{ foto.nombre }}</p>
                    <div class="card-hidden">
                        <p class="title-in">{{ foto.nombre }}</p>
                        <p>{{ foto.descripcion }}</p>

                    </div>
                </div>
                <div class="card-border"></div>
            </div>

        </div>
        {% empty %}
        <p>No hay fotos disponibles.</p>
        {% endfor %}
    </div>

</div>
</div>


</main>

{% endblock %}